[general]
name = main
; database location, check permissionexits, automatically created if not exists
dbpath = /isso/database/comments.db
; your website or blog (not the location of Isso!)
host = https://myhost.at/
; you can add multiple hosts for local development
; or SSL connections. There is no wildcard to allow
; any domain.
